<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-5ARAU77" name="com.w2a.testcases.CreateCustomerTest" tests="4" failures="1" timestamp="2022-03-09T16:06:23 IST" time="5.436" errors="0">
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="0.966" classname="com.w2a.testcases.CreateCustomerTest"/>
  <system-out/>
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="0.984" classname="com.w2a.testcases.CreateCustomerTest"/>
  <system-out/>
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="0.956" classname="com.w2a.testcases.CreateCustomerTest"/>
  <system-out/>
  <testcase name="validateCreateCustomerAPIWithInValidSecretKey" time="2.530" classname="com.w2a.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.w2a.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInValidSecretKey(CreateCustomerTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInValidSecretKey -->
  <system-out/>
</testsuite> <!-- com.w2a.testcases.CreateCustomerTest -->
